IMAGES_DIR: '/home/dsi/shaya/ct_data/OCT2017/'
RES_DIR: '/home/dsi/shaya/ct_data/res2/'

BATCH_SIZE: 32

NUM_CLASSES: 4
NUM_EPOCHS: 5
WEIGHTS: [0.56, 1.84, 2.42, 0.79]
LR: 0.001
LR_DECAY_STEP_SIZE: 17
GAMMA_DECAY: 0.6

CLUSTERING_LOSS_LAMBDA: 0
WARMUP_EPOCHS: 0