IMAGES_DIR: '/home/dsi/shaya/ct_data/OCT2017/'
RES_DIR: '/home/dsi/shaya/ct_data/res2/'

BATCH_SIZE: 32

NUM_CLASSES: 4
NUM_EPOCHS: 15
WEIGHTS: [0.56, 1.95, 2.43, 0.77]
LR: 0.001
LR_DECAY_STEP_SIZE: 17
GAMMA_DECAY: 0.6

CLUSTERING_LOSS_LAMBDA: 0.1
WARMUP_EPOCHS: 2
N_CLUSTERS: 4
TSNE_BEFORE_CLUSTERING: False